{{ if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "labels.common" . | nindent 12 }}
        spec:
          containers:
            - image: "{{ .Values.cronjob.image.registry }}/{{ .Values.cronjob.image.name }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: IfNotPresent
              name: pod-restarter
              resources: {}
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          serviceAccountName:  {{ .Values.name }}
          terminationGracePeriodSeconds: 30
  schedule: '{{ .Values.cronjob.schedule }}'
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 1
  suspend: false
{{ end }}
