kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    component: webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
      component: webhook
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
        component: webhook
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: pod-identity-webhook
          {{- if eq .Values.provider "capa" }}
          image: "{{ .Values.image.registry }}/{{ .Values.gsImage.name }}:{{ .Values.gsImage.tag }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /webhook
            - --in-cluster=false
            - --namespace={{ .Values.namespace }}
            - --service-name={{ .Values.name }}
            - --annotation-prefix={{ .Values.annotationPrefix }}
            - --token-audience={{ .Values.aws.tokenAudience }}
            - --port={{ .Values.ports.webhook }}
            - --metrics-port={{ .Values.ports.metrics }}
            - --logtostderr
            - --tls-secret={{ .Values.name }}
            - --sts-regional-endpoint
          ports:
            - name: web
              protocol: TCP
              containerPort: {{ .Values.ports.webhook }}
            - name: metrics
              protocol: TCP
              containerPort: {{ .Values.ports.metrics }}
          volumeMounts:
            - name: cert
              mountPath: "/etc/webhook/certs"
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: {{ .Values.name }}
---
