apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
webhooks:
- name: {{ .Values.name }}.amazonaws.com
  failurePolicy: Ignore
  admissionReviewVersions: [v1beta1]
  sideEffects: None
  clientConfig:
    service:
      name: {{ .Values.name }}
      namespace: {{ .Values.namespace }}
      path: "/mutate"
    caBundle: Cg==
  objectSelector:
    matchExpressions:
      - key: "app.kubernetes.io/name"
        operator: "NotIn"
        values: ["{{.Values.name}}"]
  rules:
    - operations: [ "CREATE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
- name: {{ .Values.name }}.amazonaws.com-kube-system
  failurePolicy: Ignore
  admissionReviewVersions: [v1beta1]
  sideEffects: None
  clientConfig:
    service:
      name: {{ .Values.name }}
      namespace: {{ .Values.namespace }}
      path: "/mutate"
    caBundle: Cg==
  objectSelector:
    matchExpressions:
      - key: "aws-pod-identity.giantswarm.io/force"
        operator: "Exists"
  namespaceSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: In
        values: ["kube-system"]
  rules:
    - operations: [ "CREATE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
---
