apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
webhooks:
- name: {{ .Values.name }}.amazonaws.com
  failurePolicy: Ignore
  admissionReviewVersions: [v1beta1]
  sideEffects: None
  clientConfig:
    service:
      name: {{ .Values.name }}
      namespace: {{ .Values.namespace }}
      path: "/mutate"
    caBundle: Cg==
  rules:
    - operations: [ "CREATE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
---
