apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    giantswarm.io/monitoring-port: "{{ .Values.ports.metrics }}"
    giantswarm.io/monitoring-app-label: "aws-pod-identity-webhook"
    giantswarm.io/monitoring: "true"
spec:
  ports:
  - name: web
    port: 443
    targetPort: {{ .Values.ports.webhook }}
  - name: metrics
    port: 9999
    targetPort: {{ .Values.ports.metrics }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
    component: webhook
---
