apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: 443
    targetPort: {{ .Values.ports.webhook }}
  - name: metrics
    port: 9999
    targetPort: {{ .Values.ports.metrics }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
---
