apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
  relabelings:
    - replacement: "aws-pod-identity-webhook"
      targetLabel: app
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
