version: 2.1
orbs:
  architect: giantswarm/architect@4.25.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "package and push aws-pod-identity-webhook chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "aws-pod-identity-webhook"
          filters:
            tags:
              only: /^v.*/
