version: 2.1
orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: aws-pod-identity-restarter
          filters:
            tags:
              only: /^v.*/

      # Ensure that for every commit (all branches), and for every new release tag,
      # an image is pushed to Quay.
      - architect/push-to-docker:
          context: "architect"
          name: push-to-quay
          image: "quay.io/giantswarm/aws-pod-identity-restarter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-to-docker
          image: "docker.io/giantswarm/aws-pod-identity-restarter"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # Ensure that for every commit to master, and for every new release tag,
      # an image gets pushed to the Aliyun registry.
      - architect/push-to-docker:
          context: "architect"
          name: push-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/aws-pod-identity-restarter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: "package and push aws-pod-identity-webhook chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "aws-pod-identity-webhook"
          requires:
            - push-to-aliyun
            - push-to-quay
            - push-to-docker
          filters:
            tags:
              only: /^v.*/
