name: aws-pod-identity-webhook
namespace: kube-system
serviceType: managed

# The prefix for annotations used on ServiceAccounts, e.g. `eks.amazonaws.com/role-arn`
annotationPrefix: eks.amazonaws.com

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: gsoci.azurecr.io
  name: giantswarm/amazon-eks-pod-identity-webhook
  tag: v0.6.7
  pullPolicy: IfNotPresent

# provider
# Identifies the cloud provider. This *must*
# be set. If this is installed as a default app from the default-catalog then this
# value is set dynamically and will be overridden.
provider: CHANGEME

ports:
  webhook: 9443
  metrics: 9999

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 80Mi

verticalPodAutoscaler:
  enabled: true

aws:
  tokenAudience: sts.amazonaws.com
  region: ""

restarter:
  enabled: true
  schedule: "*/5 * * * *"
  image:
    name: giantswarm/aws-pod-identity-restarter
    tag: ""
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  podSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 80Mi
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsUser: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
