name: aws-pod-identity-webhook
namespace: kube-system
serviceType: managed

# The prefix for annotations used on ServiceAccounts, e.g. `eks.amazonaws.com/role-arn`
annotationPrefix: eks.amazonaws.com

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/amazon-eks-pod-identity-webhook
  tag: v0.4.0
  pullPolicy: IfNotPresent

ports:
  webhook: 9443
  metrics: 9999

verticalPodAutoscaler:
  enabled: true

aws:
  tokenAudience: sts.amazonaws.com

cronjob:
  enabled: true
  schedule: "*/5 * * * *"
  image:
    registry: docker.io
    name: giantswarm/aws-pod-identity-restarter
    tag: [[ .Version ]]
